spring:
  datasource:
    url : jdbc:mysql://heyhong.c5ocpicx1egs.ap-northeast-2.rds.amazonaws.com:3306/HeyHong
    username : admin
    password : ghddlreogkrry1114!
    driver-class-name: com.mysql.cj.jdbc.Driver

  #    url: jdbc:h2:tcp://localhost/~/jpashop
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver